# Generated by Django 4.2.6 on 2023-10-28 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('sick', 'sick'), ('maternity', 'maternity'), ('dayoff', 'dayoff'), ('anually_leave', 'anually leave'), ('other', 'other')], max_length=30)),
                ('leave_date', models.DateField()),
                ('return_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('cancelled', 'cancelled'), ('approved', 'approved')], default='pending', max_length=30)),
                ('comment', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('sex', models.CharField(blank=True, max_length=7, null=True)),
                ('salary', models.IntegerField()),
                ('position', models.CharField(max_length=200)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='profile/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
