# Generated by Django 4.2.7 on 2024-09-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='allowed_leave',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
    ]
