# Generated by Django 4.2.6 on 2023-10-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('cancelled', 'cancelled'), ('approved', 'approved')], default='pending', max_length=30, null=True),
        ),
    ]
