# Generated by Django 4.2.7 on 2024-10-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_leave', '0002_alter_department_department_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='supervisor_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('approved', 'Approved')], default='pending', max_length=30, null=True),
        ),
    ]
