# Generated by Django 4.2.7 on 2024-09-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_leave', '0002_alter_employee_allowed_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='initial_leave',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
    ]
