# Generated by Django 4.2.6 on 2023-11-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_leave', '0003_employee_allowed_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='allowed_leave',
        ),
        migrations.AddField(
            model_name='leave',
            name='allowed_leave',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='taken_leave',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('paid_sick', 'paid sick'), ('unpaid_sick', 'unpaid sick'), ('paid_annual', 'paid annual leave'), ('unpaid_annual', 'unpaid annual leave'), ('incidental', 'incidental leave'), ('other', 'other')], max_length=30),
        ),
    ]
