# Generated by Django 4.2.7 on 2023-11-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_leave', '0004_remove_employee_allowed_leave_leave_allowed_leave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='allowed_leave',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='taken_leave',
        ),
        migrations.AddField(
            model_name='employee',
            name='allowed_leave',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='taken_leave',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
