# Generated by Django 4.2.7 on 2023-11-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_leave', '0005_remove_leave_allowed_leave_remove_leave_taken_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('paid_sick', 'Paid sick'), ('unpaid_sick', 'Unpaid sick'), ('paid_annual', 'Paid annual leave'), ('unpaid_annual', 'Unpaid annual leave'), ('incidental', 'Incidental leave'), ('other', 'other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('approved', 'Approved')], default='pending', max_length=30, null=True),
        ),
    ]
